#!/usr/bin/bash

if [[ "$1" != "" ]]; then
	feh --bg-fill "$1"
	mkdir "$HOME/.config/set-wallpaper/"
	rm -r "$HOME/.config/set-wallpaper/*"
	cp "$1" "$HOME/.config/set-wallpaper/wallpaper"
else
	feh --bg-fill "$HOME/.config/set-wallpaper/wallpaper"
fi

