#!/usr/bin/bash

if [[ "$1" != "" ]]; then
	feh --bg-fill "$1"
	mkdir "/var/set-wallpaper/"
	rm -r "/var/set-wallpaper/*"
	cp "$1" "/var/set-wallpaper/wallpaper"
else
	feh --bg-fill "/var/set-wallpaper/wallpaper"
fi

